// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TuanjieDebugVSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TuanjieDebugVSExtensionString = "88f529e6-52de-4b25-8d9f-38f396d7cd87";
        public static Guid TuanjieDebugVSExtension = new Guid(TuanjieDebugVSExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int CmdIdAttachAndDebug = 0x0100;
    }
}